limit_posts: 1
incremental: false
exclude:
  - README.md # ------------------ Basis ---------------------------
  - CNAME
  - Gemfile
  - vendor
  - package.json
  - node_modules
  - gulpfile.js
  - .stylelintrc
  - images
  - _archive
  - _trash
  - _layouts/seminar.html
  - pages/certificates
  - pages/docs
  - pages/docs/auxiliary
  - pages/indices/blog
  - pages/indices/blog-archive.html
  - _books # --------------------- Books ---------------------------
  - pages/indices/books
  - pages/indices/books.html
  - _layouts/euhandbook.html
  - _layouts/euguide.html
  - _layouts/sov.html
  - _layouts/print.html
  - _includes/booksnav.html
  - _codelog # ------------------- Code ----------------------------
  - codelog.xml
  - pages/indices/codelog.html
  - pages/indices/code.html
  - _includes/triton-syntax.scss
  - _schemes # ------------------- Schemes -------------------------
  - _includes/main.min.js
  - pages/indices/schemes.html
  - _layouts/scheme.html
  - _data/themes.yml
  - _includes/prot16-packages.html
  - _includes/prot16-palette.html
  - _includes/prot16-codedemo.html
  - _includes/prot16-codeblocks.html
  - _includes/prot16-colourorder.html
  - _includes/prot16-schemesmenu.html
  - _includes/prot16-vim-packages.html
  - _includes/prot16-project-template.md
